# Generated by Django 4.0.3 on 2022-04-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enoki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='correct_answer',
            field=models.BooleanField(null=True, verbose_name='Bonne réponse'),
        ),
    ]
