# Generated by Django 4.0.3 on 2022-04-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enoki_app', '0002_alter_answerchoice_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerchoice',
            name='id_quiz',
        ),
        migrations.RemoveField(
            model_name='answeruser',
            name='id_question',
        ),
        migrations.RemoveField(
            model_name='answeruser',
            name='id_quiz',
        ),
    ]
