# Generated by Django 4.0.3 on 2022-04-03 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enoki_app', '0003_remove_answerchoice_id_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeruser',
            name='answer_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de réponse'),
            preserve_default=False,
        ),
    ]
