# Generated by Django 4.0.3 on 2022-04-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enoki_app', '0005_alter_answeruser_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='enoki_app.quiz', verbose_name='Questionnaire'),
        ),
    ]
