# Generated by Django 4.0.3 on 2022-04-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enoki_app', '0006_alter_question_id_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='id_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_choice', to='enoki_app.question', verbose_name='Question'),
        ),
    ]
